pricing-service/views/stores.py
import json
from flask import Blueprint, render_template, request, redirect, url_for
from models.store import Store

store_blueprint = Blueprint('stores', __name__)


@store_blueprint.route('/')
def index():
    stores = Store.all()
    return render_template('stores/store_index.html', stores=stores)


@store_blueprint.route('/new', methods=['GET', 'POST'])
def create_store():
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['query'])

        Store(name, url_prefix, tag_name, query).save_to_mongo()

    # What happens if it's a GET request
    return render_template("stores/new_store.html")


@store_blueprint.route('/edit/<string:store_id>', methods=['GET', 'POST'])
def edit_store(store_id):
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['query'])

        store = Store.get_by_id(store_id)

        store.name = name
        store.url_prefix = url_prefix
        store.tag_name = tag_name
        store.query = query

        store.save_to_mongo()

        return redirect(url_for('.index'))

    # What happens if it's a GET request
    return render_template("stores/edit_store.html", store=Store.get_by_id(store_id))


@store_blueprint.route('/delete/<string:store_id>')
def delete_store(store_id):
    Store.get_by_id(store_id).remove_from_mongo()
    return redirect(url_for('.index'))



@store_blueprint.route('/<string:store_id>')
def store_page(store_id):
    return render_template('stores/store.html', store=Store.get_by_id(store_id))

pricing-service/views/users.py
from flask import Blueprint, request, session, url_for, render_template, redirect
from models.user import User, UserErrors, UserDecorators


user_blueprint = Blueprint('users', __name__)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        try:
            if User.is_login_valid(email, password):
                session['email'] = email
                return redirect(url_for(".user_alerts"))
        except UserErrors.UserError as e:
            return e.message

    return render_template("users/login.html")  # Send the user an error if their login was invalid


@user_blueprint.route('/register', methods=['GET', 'POST'])
def register_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        try:
            if User.register_user(email, password):
                session['email'] = email
                return redirect(url_for(".user_alerts"))
        except UserErrors.UserError as e:
            return e.message

    return render_template("users/register.html")  # Send the user an error if their login was invalid


@user_blueprint.route('/alerts')
@UserDecorators.requires_login
def user_alerts():
    user = User.find_by_email(session['email'])
    return render_template("users/alerts.html", alerts=user.get_alerts())


@user_blueprint.route('/logout')
def logout_user():
    session['email'] = None
    return redirect(url_for('home'))


@user_blueprint.route('/check_alerts/<string:user_id>')
@UserDecorators.requires_login
def check_user_alerts(user_id):
    pass

pricing-service/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Price Alerts</title>

    {% include 'html_dependencies.html' %}
  </head>
  <body>
    <nav class="navbar navbar-fixed-top navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button
            type="button"
            class="navbar-toggle collapsed"
            data-toggle="collapse"
            data-target="#navbar"
            aria-expanded="false"
            aria-controls="navbar"
          >
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span> <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/" title="Home">Pricing</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li>
              <a href="{{ url_for('stores.index') }}" title="Stores">Stores</a>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if session['email'] %}
            <li>
              <a href="{{ url_for('users.user_alerts') }}" title="Your Alerts">
                <span class="glyphicon glyphicon-user"></span> Your Alerts
              </a>
            </li>
            <li>
              <a href="{{ url_for('users.logout_user') }}" title="Log Out">
                <span class="glyphicon glyphicon-log-out"></span> Log out
              </a>
            </li>
            {% else %}
            <li>
              <a href="{{ url_for('users.register_user') }}" title="Sign up">
                <span class="glyphicon glyphicon-user"></span> Sign up
              </a>
            </li>
            <li>
              <a href="{{ url_for('users.login_user') }}" title="Log in">
                <span class="glyphicon glyphicon-log-in"></span> Log in
              </a>
            </li>
            {% endif %}
          </ul>
          ​
        </div>
      </div>
    </nav>

    <div class="content container">{% block content %} {% endblock %}</div>
  </body>
</html>

pricing-service/templates/home.html
{% extends "base.html" %} {% block content %}
<div class="jumbotron">
  <h1>Pricing Service</h1>
  <p>
    We scan online store websites to alert you of price drops in items that
    interest you.
  </p>
  <p>
    Just sign up, and get started by adding the URL of an item that you wish to
    track. We'll do the rest!
  </p>
  <p>
    <a
      class="btn btn-primary btn-lg"
      href="{{ url_for('users.register_user') }}"
      role="button"
    >Get started</a>
  </p>
</div>
{% endblock %}

pricing-service/templates/html_dependencies.html
<link
  rel="stylesheet"
  href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"
/>
<link
  rel="stylesheet"
  href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
/>
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/style.css') }}"
/>
<script src="http://code.jquery.com/jquery-2.2.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>