pricing-service/models/store/__init__.py
from models.store.store import Store
import models.store.errors as StoreErrors

pricing-service/views/stores.py
import json
from flask import Blueprint, render_template, request, redirect, url_for
from models.store import Store

store_blueprint = Blueprint('stores', __name__)


@store_blueprint.route('/')
def index():
    stores = Store.all()
    return render_template('stores/store_index.html', stores=stores)


@store_blueprint.route('/new', methods=['GET', 'POST'])
def create_store():
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['query'])

        Store(name, url_prefix, tag_name, query).save_to_mongo()

    # What happens if it's a GET request
    return render_template("stores/new_store.html")


@store_blueprint.route('/edit/<string:store_id>', methods=['GET', 'POST'])
def edit_store(store_id):
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['query'])

        store = Store.get_by_id(store_id)

        store.name = name
        store.url_prefix = url_prefix
        store.tag_name = tag_name
        store.query = query

        store.save_to_mongo()

        return redirect(url_for('.index'))

    # What happens if it's a GET request
    return render_template("stores/edit_store.html", store=Store.get_by_id(store_id))


@store_blueprint.route('/delete/<string:store_id>')
def delete_store(store_id):
    Store.get_by_id(store_id).remove_from_mongo()
    return redirect(url_for('.index'))



@store_blueprint.route('/<string:store_id>')
def store_page(store_id):
    return render_template('stores/store.html', store=Store.get_by_id(store_id))

pricing-service/templates/stores/edit_store.html
{% extends "base.html" %} {% block content %}
<div class="page-header">
    <h1>Edit Store</h1>
</div>
<div class="form">
    <form method="post">
        <div class="form-group">
            <label for="name">Store name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Name" value="{{ store.name }}" />
        </div>
        <div class="form-group">
            <label for="url_prefix">Store URL Prefix</label>
            <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="http://..."
                aria-describedby="storeURLPrefixHelp" value="{{ store.url_prefix }}" />
            <span id="storeURLPrefixHelp" class="help-block">
                What characters do URLs of all items in this online store start with?
            </span>
        </div>
        <div class="form-group">
            <label for="tag_name">Tag name</label>
            <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="span" aria-describedby="tagNameHelp"
                value="{{ store.tag_name }}" />
            <span id="tagNameHelp" class="help-block">
                What is the HTML tag of the item that contains the item price? (usually 'span')
            </span>
        </div>
        <div class="form-group">
            <label for="query">Query</label>
            <input type="text" class="form-control" id="query" name="query" placeholder="{&quot;id&quot;: &quot;...&quot;}"
                aria-describedby="queryHelpBlock" value="{{ store.query | tojson }}" />
            <!-- If using double quotes here, it breaks! -->
            <span id="queryHelpBlock" class="help-block">
                What JSON query would we have to do to find the specific tag with the price?
            </span>
        </div>
        <button type="submit" class="btn btn-warning">Update</button>
    </form>
</div>
{% endblock %}

pricing-service/templates/stores/new_store.html
{% extends "base.html" %}
{% block content %}
<div class="page-header">
    <h1>Create Store</h1>
</div>
<div class="form">
    <form method="post">
        <div class="form-group">
            <label for="name">Store name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Name">
        </div>
        <div class="form-group">
            <label for="url_prefix">Store URL Prefix</label>
            <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="http://..."
                aria-describedby="storeURLPrefixHelp">
            <span id="storeURLPrefixHelp" class="help-block">
                What characters do URLs of all items in this online store start with?
            </span>
        </div>
        <div class="form-group">
            <label for="tag_name">Tag name</label>
            <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="span" value="span"
                aria-describedby="tagNameHelp">
            <span id="tagNameHelp" class="help-block">
                What is the HTML tag of the item that contains the item price? (usually 'span')
            </span>
        </div>
        <div class="form-group">
            <label for="query">Query</label>
            <input type="text" class="form-control" id="query" name="query" placeholder='{"id": "..."}'
                aria-describedby="queryHelpBlock">
            <span id="queryHelpBlock" class="help-block">
                What JSON query would we have to do to find the specific tag with the price?
            </span>
        </div>
        <button type="submit" class="btn btn-default">Create</button>
    </form>
</div>
{% endblock %}

pricing-service/templates/stores/store.html
{% extends "base.html" %}
{% block content %}
<div class="page-header">
    <h1>Store
        <small>{{ store.name }}</small>
    </h1>
</div>
<p>All URLs in this store should start with <strong>{{ store.url_prefix }}</strong></p>
{% if session['email'] in config.ADMIN %}
<div class="panel panel-default">
    <div class="panel-body">
        <a class="btn btn-warning" href="{{ url_for('stores.edit_store', store_id=store._id) }}" role="button">
            Edit Store
        </a>
        <a class="btn btn-danger" href="{{ url_for('stores.delete_store', store_id=store._id) }}" role="button">
            Permanently Delete Store
        </a>
    </div>
</div>
{% endif %}
{% endblock %}

pricing-service/templates/stores/store_index.html
{% extends "base.html" %}
{% block content %}
<div class="page-header">
    <h1>Stores
        <small>list of stores supported</small>
    </h1>
</div>
<div class="list-group">
    {% for store in stores %}
    <a href="{{ url_for('stores.store_page', store_id=store._id) }}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ store.name }}</h4>
        <p >All URLs in this store should start with
            <strong>{{ store.url_prefix }}</strong></p>
    </a>
    {% endfor %}
</div>
{% if session['email'] in config.ADMIN %}
<a class="btn btn-success" href="{{ url_for('stores.create_store') }}">
    <span class="glyphicon glyphicon-plus"></span> Create new
</a>
{% endif %}
{% endblock %}