pricing-service/models/alert.py
from dataclasses import dataclass, field
from typing import List, Dict
from flask import current_app
import uuid
import datetime
import requests
from models.model import Model
from common.database import Database
from models.item import Item


@dataclass(eq=False)
class Alert(Model):
    collection: str = field(init=False, default="alerts")
    user_email: str
    price_limit: str
    item_id: str
    active: bool = True
    last_checked: datetime.datetime = field(default_factory=datetime.datetime.utcnow)
    _id: str = field(default_factory=lambda: uuid.uuid4().hex)

    def __post_init__(self):
        self.item = Item.get_by_id(self.item_id)

    def send(self) -> requests.Request:
        return requests.post(
            current_app.config.MAILGUN_URL,
            auth=("api", current_app.config.MAILGUN_API_KEY),
            data={
                "from": current_app.config.MAILGUN_FROM,
                "to": self.user_email,
                "subject": "Price limit reached for {}".format(self.item.name),
                "text": "We've found a deal! ({}).".format(self.item.url),
            },
        )

    @classmethod
    def find_needing_update(cls, minutes_since_update: int) -> List["Alert"]:
        last_updated_limit = datetime.datetime.utcnow() - datetime.timedelta(
            minutes=minutes_since_update
        )
        return [
            cls(**elem)
            for elem in Database.find(
                cls.collection,
                {"last_checked": {"$lte": last_updated_limit}, "active": True},
            )
        ]

    def json(self) -> Dict:
        return {
            "_id": self._id,
            "price_limit": self.price_limit,
            "last_checked": self.last_checked,
            "user_email": self.user_email,
            "item_id": self.item._id,
            "active": self.active,
        }

    def load_item_price(self) -> float:
        self.item.load_price()
        self.last_checked = datetime.datetime.utcnow()
        self.item.save_to_mongo()
        self.save_to_mongo()
        return self.item.price

    def send_email_if_price_reached(self) -> None:
        if self.item.price < self.price_limit:
            self.send()

    @classmethod
    def find_by_user_email(cls, user_email: str) -> List["Alert"]:
        return cls.find_many_by("user_email", user_email)

    def deactivate(self) -> None:
        self.active = False
        self.save_to_mongo()

    def activate(self) -> None:
        self.active = True
        self.save_to_mongo()

pricing-service/views/alerts.py
from flask import Blueprint, request, render_template, session, redirect, url_for

from models.alert import Alert
from models.item import Item
from models.user import UserDecorators


alert_blueprint = Blueprint('alerts', __name__)


@alert_blueprint.route('/new', methods=['GET', 'POST'])
@UserDecorators.requires_login
def create_alert():
    if request.method == 'POST':
        name = request.form['name']
        url = request.form['url']
        price_limit = float(request.form['price_limit'])

        item = Item(name, url)
        item.save_to_mongo()

        alert = Alert(session['email'], price_limit, item._id)
        alert.load_item_price()  # This already saves to MongoDB

    # What happens if it's a GET request
    return render_template("alerts/new_alert.html")  # Send the user an error if their login was invalid


@alert_blueprint.route('/edit/<string:alert_id>', methods=['GET', 'POST'])
@UserDecorators.requires_login
def edit_alert(alert_id):
    if request.method == 'POST':
        price_limit = float(request.form['price_limit'])

        alert = Alert.get_by_id(alert_id)
        alert.price_limit = price_limit
        alert.load_item_price()  # This already saves to MongoDB

    # What happens if it's a GET request
    return render_template("alerts/edit_alert.html", alert=Alert.get_by_id(alert_id))  # Send the user an error if their login was invalid


@alert_blueprint.route('/deactivate/<string:alert_id>')
@UserDecorators.requires_login
def deactivate_alert(alert_id):
    Alert.get_by_id(alert_id).deactivate()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/activate/<string:alert_id>')
@UserDecorators.requires_login
def activate_alert(alert_id):
    Alert.get_by_id(alert_id).activate()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/delete/<string:alert_id>')
@UserDecorators.requires_login
def delete_alert(alert_id):
    Alert.get_by_id(alert_id).remove_from_mongo()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/<string:alert_id>')
@UserDecorators.requires_login
def get_alert_page(alert_id):
    return render_template('alerts/alert.html', alert=Alert.get_by_id(alert_id))


@alert_blueprint.route('/check_price/<string:alert_id>')
def check_alert_price(alert_id):
    Alert.get_by_id(alert_id).load_item_price()
    return redirect(url_for('.get_alert_page', alert_id=alert_id))

pricing-service/templates/alerts/alert.html
{% extends "base.html" %}
{% block content %}
<div class="page-header">
    <h1>Alert
        <small>for '{{ alert.item.name }}'</small>
    </h1>
</div>
<p>Last price found <strong>£{{ alert.item.price }}</strong></p>
<p>Last checked on <strong>{{ alert.last_checked.strftime("%d-%m-%Y %H:%M") }}</strong></p>
<div class="panel panel-default">
    <div class="panel-body">
        <a class="btn btn-default" href="{{ alert.item.url }}" role="button">Visit Site</a>
        <a class="btn btn-default" href="{{ url_for('alerts.edit_alert', alert_id=alert._id) }}" role="button">
            Edit Alert
        </a>
        {% if alert.active %}
        <a class="btn btn-danger" href="{{ url_for('alerts.deactivate_alert', alert_id=alert._id) }}" role="button">
            Deactivate Alert
        </a>
        {% else %}
        <a class="btn btn-success" href="{{ url_for('alerts.activate_alert', alert_id=alert._id) }}" role="button">
            Activate Alert
        </a>
        <a class="btn btn-danger" href="{{ url_for('alerts.delete_alert', alert_id=alert._id) }}" role="button">
            Permanently Delete Alert
        </a>
        {% endif %}
        <a class="btn btn-warning" href="{{ url_for('alerts.check_alert_price', alert_id=alert._id) }}" role="button">
            Check Price Now
        </a>
    </div>
</div>
{% endblock %}

pricing-service/templates/alerts/edit_alert.html
{% extends "base.html" %}
{% block content %}
<div class="page-header">
    <h1>Edit Alert</h1>
</div>
<div class="form">
    <form method="post">
        <div class="form-group">
            <label for="name">Alert/Item Name</label>
            <input type="text" class="form-control" id="name" name="name" value="{{ alert.item.name }}" disabled>
        </div>
        <div class="form-group">
            <label for="url">Item URL</label>
            <input type="text" class="form-control" id="url" name="url" value="{{ alert.item.url }}" disabled>
        </div>
        <div class="form-group">
            <label for="price_limit">Alert limit</label>
            <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder="45.0" aria-describedby="priceLimitBlock" value="{{ alert.price_limit }}">
            <span id="priceLimitBlock" class="help-block">
                We'll send you an e-mail when the price reaches or goes under this.
            </span>
        </div>
        <button type="submit" class="btn btn-default">Update</button>
    </form>
</div>
{% endblock %}

pricing-service/templates/alerts/new_alert.html
{% extends "base.html" %}
{% block content %}
<div class="page-header">
    <h1>Create Alert</h1>
</div>
<div class="form">
    <form method="post">
        <div class="form-group">
            <label for="name">Alert/Item Name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Name">
        </div>
        <div class="form-group">
            <label for="url">Item URL</label>
            <input type="text" class="form-control" id="url" name="url" placeholder="http://...">
        </div>
        <div class="form-group">
            <label for="price_limit">Alert limit</label>
            <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder="45.0" aria-describedby="priceLimitBlock">
            <span id="priceLimitBlock" class="help-block">
                We'll send you an e-mail when the price reaches or goes under this.
            </span>
        </div>
        <button type="submit" class="btn btn-default">Create</button>
    </form>
</div>
{% endblock %}